export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const SHOW_TRANSACTION_CREATION_MODAL =
  'SHOW_TRANSACTION_CREATION_MODAL';
export const SET_DEFAULT = 'SET_DEFAULT';
